"""Initial Generation

Revision ID: 00dc9a6b00ce
Revises: 
Create Date: 2024-06-16 20:14:36.995357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc9a6b00ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('img_class', sa.String(), nullable=True),
    sa.Column('img_concept', sa.String(), nullable=True),
    sa.Column('img_concept_id', sa.Integer(), nullable=True),
    sa.Column('img_things_concept_id', sa.Integer(), nullable=True),
    sa.Column('img_condition', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
