model:
  device: cuda
  target: src.eeg_encoders.models.visualencoder.VisualEncoder
  modules:
    temporal:
      in_channels: [1, 1, 1]
      out_channels: [6, 6, 6]
      kernel_sizes: [9, 9, 9]
      strides: [1, 1, 1]
      paddings: [4, 8, 16]
      dilations: [1, 2, 4]
      conv_count: 3
    spatial:
      in_channels: [18, 18, 18, 18]
      out_channels: [2, 2, 2, 2]
      kernel_sizes: [63, 31, 15, 7]
      strides: [1, 1, 1, 1]
      paddings: [31, 15, 7, 3]
      dilations: [1, 1, 1, 1]
      conv_count: 4
    residual:
      in_channels: [[8, 8], [8, 8], [8, 8]]
      out_channels: [[8, 8], [8, 8], [8, 8]]
      kernel_sizes: [[3, 3], [3, 3], [3, 3]]
      strides: [[1, 1], [1, 1], [1, 1]]
      dilations: [[1, 1], [1, 1], [1, 1]]
      paddings: [[1, 1], [1, 1], [1, 1]]
      pool_sizes: [[2, 1], [2, 1], [2, 1]] #  -> (7, 12)
      input_pool_size: [2, 2, 2]
      conv_count: 2
      layer_count: 3
    fc:
      in_channels: 8
      out_channels: 1
      kernel_size: 2 # (6, 11)
      stride: 1
      padding: 0
      dilation: 1
      in_features: 180
      inter_features: None
      inter_layers: 0
      out_features: 768
      up_in_channels: None
      up_out_channels: None
      up_kernel_size: None
      up_stride: None
      up_padding: None
      up_layers: 0